### ISSUE TITLE
Command injection inside the ping command

### ISSUE THREAD

**Issue by guillaumemichel** [CedMaire/grass#11]
There is no proper sanitization of the input to the command `ping` before the call to `popen`, thus it is possible to execute arbitrary command after adding a ';' to the parameter of the ping command.
Location: server.c, line 521 (ping command), server.c, line 119 (popen)

Here is the input to give to the client to open a calculator
```
>>> ping ;xcalc
```

**Comment by CedMaire** [comment]
Duplicate of #10. Approved.
